repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=100"]
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
        exclude_types: ["image"]
      - id: trailing-whitespace
        exclude_types: ["image"]
      - id: requirements-txt-fixer
        files: (requirements|constraints).*\.(txt|in)$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.5
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.7
    hooks:
      - id: clang-format
        "types_or": [c++, c]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-tabs
        exclude: ".gitmodules|Makefile"

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint

  - repo: https://github.com/shellcheck-py/shellcheck-py # TODO add this
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        exclude: build_tools/credential-helper # This is an autogenerated file

  - repo: local
    hooks:
      - id: buildifier
        name: buildifier
        entry: buildifier
        language: golang
        additional_dependencies: [
            # v7.1.2
            "github.com/bazelbuild/buildtools/buildifier@1429e15ae755a6762d0edf9198062dc6ed04408d",
          ]
        files: '^(.*/)?(BUILD\.bazel|BUILD|WORKSPACE|WORKSPACE\.bazel|WORKSPACE\.bzlmod|MODULE\.bazel)$|\.BUILD$|\.bzl$'
        language_version: "1.16"
      - id: build_file_names
        name: Check Bazel file names
        entry: Files should be named BUILD.bazel instead of BUILD
        language: fail
        files: "BUILD$"
